In [2]:
import numpy as np
import  numpy.random as rd

In [4]:
rd.randint(1,7)

4

In [2]:
number = [1,2,3,4,5,6]
rd.choice(number)

2

In [10]:
dies = rd.randint(1,7,10)
dies

array([4, 6, 3, 3, 3, 1, 1, 6, 5, 5])

In [124]:
number = [1,2,3,4,5,6]
dies = rd.choice(number,10)
dies

array([2, 1, 5, 3, 5, 5, 2, 4, 6, 5])

In [43]:
dies = rd.randint(1,7,10000)

In [45]:
def func_count(x):
    result = dict()
    number = np.unique(x)
    for n in number:
        result[n] = x[x == n].size
    return result

In [46]:
func_count(dies)

{1: 1696, 2: 1679, 3: 1635, 4: 1687, 5: 1649, 6: 1654}

In [47]:
die_1 = rd.randint(1,7,10000)
die_2 = rd.randint(1,7,10000)
die_sum = die_1 + die_2

In [48]:
func_count(die_sum)

{2: 262,
 3: 578,
 4: 799,
 5: 1121,
 6: 1398,
 7: 1618,
 8: 1467,
 9: 1082,
 10: 844,
 11: 563,
 12: 268}

In [50]:
def func_prob(x):
    result = dict()
    number = np.unique(x)
    for n in number:
        result[n] = x[x == n].size/len(x)
    return result

In [51]:
func_prob(die_sum)

{2: 0.0262,
 3: 0.0578,
 4: 0.0799,
 5: 0.1121,
 6: 0.1398,
 7: 0.1618,
 8: 0.1467,
 9: 0.1082,
 10: 0.0844,
 11: 0.0563,
 12: 0.0268}

In [10]:
die = rd.randint(1,7,10)
die
die==5

array([False, False, False, False, False, False, False, False, False,
       False])

In [5]:
test_num = 10000
die_1 = rd.randint(1,7,test_num)
die_2 = rd.randint(1,7,test_num)
result = (die_1 == 5) & (die_2 == 5)
sim_prob = result.sum()/test_num
print("模拟概率为{x:.4f}".format(x=sim_prob))

模拟概率为0.0284


In [2]:
real_prob = (1/6)*(1/6)
print("真实概率为{x:.4f}".format(x=real_prob))

真实概率为0.0278


In [125]:
test_num = 10000
coin_1 = rd.randint(0,2,test_num)
coin_2 = rd.randint(0,2,test_num)
coin_3 = rd.randint(0,2,test_num)

In [128]:
result_1 = (coin_1 == 1) & (coin_2 == 1) & (coin_3 == 1)
result_2 = (coin_1 == 0) & (coin_2 == 0) & (coin_3 == 0)
(result_1.sum()+result_2.sum())/test_num

0.2527

In [131]:
test_num = 10000
coin_1 = rd.randint(0,2,test_num)
coin_2 = rd.randint(0,2,test_num)
result_1 = (coin_1 == 1) & (coin_2 == 1)
result_2 = (coin_1 == 0) & (coin_2 == 0)
result_3 = ((coin_1 == 0) & (coin_2 == 1)) | ((coin_1 == 1) & (coin_2 == 0))

In [132]:
print(result_1.sum())
print(result_2.sum())
print(result_3.sum())

2550
2431
5019


In [133]:
amt_result = 3*result_1+1*result_2 +(-2)*result_3

In [134]:
amt_result.sum()

43

In [135]:
test_num = 10000
coin_1 = rd.randint(0,2,test_num)
coin_2 = np.zeros(test_num)
result_1 = (coin_1 == 1) & (coin_2 == 1)
result_2 = (coin_1 == 0) & (coin_2 == 0)
result_3 = ((coin_1 == 0) & (coin_2 == 1)) | ((coin_1 == 1) & (coin_2 == 0))
amt_result = 3*result_1+1*result_2 +(-2)*result_3
amt_result.sum()

-4991

In [9]:
suit = ['红心','黑桃','方片','草花']
number = ['2','3','4','5','6','7','8','9','10','J','Q','K','A']
cards = np.array([{'s':s,'n':n} for s in suit for n in number])

In [10]:
cards[:4]

array([{'s': '红心', 'n': '2'}, {'s': '红心', 'n': '3'},
       {'s': '红心', 'n': '4'}, {'s': '红心', 'n': '5'}], dtype=object)

In [11]:
my_card = rd.choice(cards, 2,replace=False)

In [12]:
my_card

array([{'s': '黑桃', 'n': '10'}, {'s': '红心', 'n': 'J'}], dtype=object)

In [15]:
def cards_func():
    my_card = rd.choice(cards, 2,replace=False)
    is_AA = my_card[0]['n'] == 'A' and my_card[1]['n'] == 'A'
    return is_AA

In [16]:
test_num = 10000
result = np.array([cards_func() for x in range(test_num)])

In [18]:
sim_prob = result.sum()/test_num
print("模拟概率为{x:.4f}".format(x=sim_prob))

模拟概率为0.0047


In [19]:
real_prob = (4/52)*(3/51)
print("真实概率为{x:.4f}".format(x=real_prob))

真实概率为0.0045


In [13]:
suit = ['红心','黑桃','方片','草花']
number = ['2','3','4','5','6','7','8','9','10','J','Q','K','A']
cards = np.array([{'s':s,'n':n} for s in suit for n in number])

In [26]:
def cards_func():
    my_card = rd.choice(cards, 5,replace=False)
    is_fore = len(set([c['n'] for c in my_card]))==2
    return is_fore

In [27]:
test_num = 10000
result = np.array([cards_func() for x in range(test_num)])

In [29]:
sum(result)/10000

0.0016

In [4]:
def find_pi(n):
    x = rd.rand(n)
    y = rd.rand(n)
    dist = np.sqrt((x-0.5)**2 +(y-0.5)**2)
    inside = dist<0.5
    pi = (inside.sum()/n)/0.25
    return pi

In [5]:
find_pi(1000000)

3.140796